import { AcademicCurriculum, AcademicChapter } from "../types";
import {
  chapter01,
  chapter02,
  chapter03,
  chapter04,
  chapter05,
} from "./machine-learning/chunk1-foundations";

/**
 * KURIKULUM AKADEMIK RESMI: MATEMATIKA & STATISTIKA UNTUK AI
 * Standar: University-Grade / Advanced Engineering Curriculum
 * Rujukan Kanonikal: Hastie, Tibshirani, Friedman (ESL); Kevin P. Murphy (PML);
 * Stephen Boyd & Lieven Vandenberghe (Convex Optimization); Tom M. Mitchell (ML).
 * 
 * Materi disalin dari Fondasi chunk1-foundations.ts (Bab 1 - 5, 38 Subbab Asimetris Kanonikal)
 * tanpa menghapus berkas sumber aslinya.
 */

// Adaptasi bab dengan ID dan Slug unik untuk mencegah tabrakan rute dengan modul Machine Learning
export const mathStatChapters: AcademicChapter[] = [
  {
    ...chapter01,
    id: "math-stat-ch-01",
    slug: "bab-01-paradigma-komputasi-perumusan-masalah-ilmiah",
    title: "Bab 1: Paradigma Komputasi & Perumusan Masalah Ilmiah",
    orderIndex: 1,
    subchapters: chapter01.subchapters.map((sub, idx) => ({
      ...sub,
      id: `math-01-${idx + 1}`,
      slug: `math-01-${idx + 1}-${sub.slug.replace(/^\d+-\d+-?/, "")}`,
    })),
  },
  {
    ...chapter02,
    id: "math-stat-ch-02",
    slug: "bab-02-aljabar-linier-komputasional-kalkulus-matriks",
    title: "Bab 2: Aljabar Linier Komputasional & Kalkulus Matriks",
    orderIndex: 2,
    subchapters: chapter02.subchapters.map((sub, idx) => ({
      ...sub,
      id: `math-02-${idx + 1}`,
      slug: `math-02-${idx + 1}-${sub.slug.replace(/^\d+-\d+-?/, "")}`,
    })),
  },
  {
    ...chapter03,
    id: "math-stat-ch-03",
    slug: "bab-03-teori-probabilitas-estimasi-parameter-bayesian-inference",
    title: "Bab 3: Teori Probabilitas, Estimasi Parameter, & Bayesian Inference",
    orderIndex: 3,
    subchapters: chapter03.subchapters.map((sub, idx) => ({
      ...sub,
      id: `math-03-${idx + 1}`,
      slug: `math-03-${idx + 1}-${sub.slug.replace(/^\d+-\d+-?/, "")}`,
    })),
  },
  {
    ...chapter04,
    id: "math-stat-ch-04",
    slug: "bab-04-teori-belajar-statistik-dekomposisi-bias-variance",
    title: "Bab 4: Teori Belajar Statistik & Dekomposisi Bias-Variance",
    orderIndex: 4,
    subchapters: chapter04.subchapters.map((sub, idx) => ({
      ...sub,
      id: `math-04-${idx + 1}`,
      slug: `math-04-${idx + 1}-${sub.slug.replace(/^\d+-\d+-?/, "")}`,
    })),
  },
  {
    ...chapter05,
    id: "math-stat-ch-05",
    slug: "bab-05-optimasi-numerik-untuk-machine-learning",
    title: "Bab 5: Optimasi Numerik untuk Machine Learning & AI",
    orderIndex: 5,
    subchapters: chapter05.subchapters.map((sub, idx) => ({
      ...sub,
      id: `math-05-${idx + 1}`,
      slug: `math-05-${idx + 1}-${sub.slug.replace(/^\d+-\d+-?/, "")}`,
    })),
  },
  {
    id: "math-stat-ch-06",
    slug: "bab-06-dekomposisi-spektral-matriks-eigendecomposition-svd",
    title: "Bab 6: Dekomposisi Spektral Matriks: Eigendecomposition & SVD",
    orderIndex: 6,
    description: "Dekomposisi spektral matriks kovariansi, nilai eigen dan vektor eigen, faktorisasi nilai singular (Singular Value Decomposition / SVD), serta kompresi informasi Principal Component Analysis (PCA).",
    subchapters: [
      {
        id: "math-06-1",
        slug: "math-06-1-nilai-eigen-vektor-eigen",
        title: "6.1 Nilai Eigen, Vektor Eigen, & Transformasi Ruang Karakteristik",
        orderIndex: 1,
        description: "Persamaan karakteristik det(A - λI) = 0, diagonalisasi matriks simetris, dan interpretasi geometris elipsoid transformasi.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-06-2",
        slug: "math-06-2-singular-value-decomposition-svd",
        title: "6.2 Faktorisasi Nilai Singular (Singular Value Decomposition / SVD)",
        orderIndex: 2,
        description: "Teorema dekomposisi A = UΣV^T, pseudoinverse Moore-Penrose, dan aproksimasi rank rendah Eckart-Young-Mirsky.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-06-3",
        slug: "math-06-3-reduksi-dimensi-pca",
        title: "6.3 Reduksi Dimensi & Kompresi Informasi Principal Component Analysis (PCA)",
        orderIndex: 3,
        description: "Maksimisasi varians proyeksi, matriks kovariansi empiris, scree plot, dan rekonstruksi loss kuadrat terkecil.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
    ],
  },
  {
    id: "math-stat-ch-07",
    slug: "bab-07-estimasi-parameter-lanjutan-mle-map",
    title: "Bab 7: Estimasi Parameter Lanjutan (MLE & MAP) & Teori Asimtotik",
    orderIndex: 7,
    description: "Prinsip estimasi likelihood maksimum (MLE), fungsi log-likelihood, informasi Fisher, estimasi bayesian MAP dengan conjugate priors, dan sifat asimtotik konsistensi estimator.",
    subchapters: [
      {
        id: "math-07-1",
        slug: "math-07-1-maximum-likelihood-estimation-fisher-info",
        title: "7.1 Prinsip Maximum Likelihood Estimation (MLE) & Fisher Information",
        orderIndex: 1,
        description: "Perumusan log-likelihood, skor gradien analitis, matriks informasi Fisher, dan batas Cramer-Rao Lower Bound (CRLB).",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-07-2",
        slug: "math-07-2-maximum-a-posteriori-conjugate-priors",
        title: "7.2 Estimasi Maximum A Posteriori (MAP) & Distribusi Prior Konjugat",
        orderIndex: 2,
        description: "Integrasi prior belief P(θ), regularisasi L2 sebagai Gaussian prior, regularisasi L1 sebagai Laplace prior, dan conjugate priors.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-07-3",
        slug: "math-07-3-teorema-limit-pusat-sifat-asimtotik",
        title: "7.3 Teorema Limit Pusat (CLT) & Sifat-Sifat Estimator Asimtotik",
        orderIndex: 3,
        description: "Hukum bilangan besar (LLN), konvergensi dalam distribusi, konsistensi estimator, efisiensi asimtotik, dan normalitas asimtotik MLE.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
    ],
  },
  {
    id: "math-stat-ch-08",
    slug: "bab-08-uji-hipotesis-statistik-ab-testing",
    title: "Bab 8: Uji Hipotesis Statistik, A/B Testing, & Inferensi Kausal",
    orderIndex: 8,
    description: "Pengujian hipotesis statistik inferensial, formulasi H0 vs H1, kesalahan Tipe I dan Tipe II, uji parametrik dan non-parametrik, metodologi eksperimen A/B testing industri, dan kekuatan statistik (Statistical Power).",
    subchapters: [
      {
        id: "math-08-1",
        slug: "math-08-1-perumusan-hipotesis-p-value-alpha-beta",
        title: "8.1 Perumusan Hipotesis Null/Alternatif, Nilai p-Value, & Kesalahan Tipe I/II",
        orderIndex: 1,
        description: "Signifikansi statistik α, probabilitas false positive, statistical power (1 - β), dan batas interpretasi p-value.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-08-2",
        slug: "math-08-2-uji-parametrik-non-parametrik",
        title: "8.2 Uji Signifikansi Parametrik & Non-Parametrik (t-Test, Z-Test, ANOVA, Chi-Square)",
        orderIndex: 2,
        description: "Two-sample t-test Welch, uji proporsi Z, One-Way ANOVA F-test, Mann-Whitney U test, dan uji kebebasan Chi-Square.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-08-3",
        slug: "math-08-3-metodologi-ab-testing-power-analysis",
        title: "8.3 Metodologi A/B Testing Industri, Sample Size Determination, & Statistical Power",
        orderIndex: 3,
        description: "Minimum Detectable Effect (MDE), penentuan ukuran sampel, randomisasi kelompok kontrol/perlakuan, dan koreksi Bonferroni.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
    ],
  },
  {
    id: "math-stat-ch-09",
    slug: "bab-09-teori-informasi-entropi-cross-entropy-kl-divergence",
    title: "Bab 9: Teori Informasi: Entropi Shannon, Cross-Entropy, & Divergensi KL",
    orderIndex: 9,
    description: "Pengukuran kuantitatif informasi, entropi Shannon untuk distribusi diskrit/kontinu, mutual information, cross-entropy loss klasifikasi, dan divergensi Kullback-Leibler (KL) sebagai ukuran jarak distribusi probabilitas.",
    subchapters: [
      {
        id: "math-09-1",
        slug: "math-09-1-entropi-shannon-ketidakpastian-informasi",
        title: "9.1 Entropi Shannon & Ketidakpastian Informasi",
        orderIndex: 1,
        description: "Fungsi surprizal -log2(p), kompresi data lossless, batas entropis, dan entropi diferensial untuk variabel acak kontinu.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-09-2",
        slug: "math-09-2-cross-entropy-loss-klasifikasi",
        title: "9.2 Cross-Entropy & Perumusan Fungsi Loss Klasifikasi Multikelas",
        orderIndex: 2,
        description: "Hubungan antara MLE dan minimisasi cross-entropy loss, fungsi softmax, dan sifat optimasi gradien numerik.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-09-3",
        slug: "math-09-3-divergensi-kullback-leibler-relative-entropy",
        title: "9.3 Divergensi Kullback-Leibler (KL) & Relative Entropy pada Model Probabilistik",
        orderIndex: 3,
        description: "Sifat asimetris D_KL(P||Q), ketidaksamaan Gibbs, aplikasi pada Variational Autoencoder (VAE) dan t-SNE.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
    ],
  },
  {
    id: "math-stat-ch-10",
    slug: "bab-10-formulasi-matematis-algoritma-ml-scratch-engine",
    title: "Bab 10: Formulasi Matematis Algoritma ML & Penurunan Gradien dari Nol (Capstone)",
    orderIndex: 10,
    description: "Penurunan matematis analitis fungsi loss kuadratik (MSE) dan log-loss, matriks Hessian, syarat keoptimalan orde pertama/kedua, serta penyusunan mesin komputasi matematis murni (Scratch Engine) dengan NumPy.",
    subchapters: [
      {
        id: "math-10-1",
        slug: "math-10-1-penurunan-analitis-gradien-loss-function",
        title: "10.1 Penurunan Analitis Gradien Loss Function (Regresi Linier & Logistik)",
        orderIndex: 1,
        description: "Kalkulus vektor matriks dJ/dw, persamaan normal OLS (X^T X)^(-1) X^T y, dan penurunan gradien sigmoid.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-10-2",
        slug: "math-10-2-matriks-hessian-metode-orde-kedua",
        title: "10.2 Matriks Hessian & Metode Optimasi Orde Kedua (Newton-Raphson)",
        orderIndex: 2,
        description: "Kelengkungan fungsi, matriks Hessian semidefinit positif, pembaruan langkah Newton w_(t+1) = w_t - H^(-1) g, dan batas komputasi O(d^3).",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
      {
        id: "math-10-3",
        slug: "math-10-3-capstone-mesin-komputasi-matematis-numpy",
        title: "10.3 Capstone: Pemrograman Mesin Komputasi Matematis Murni Berbasis NumPy",
        orderIndex: 3,
        description: "Pembangunan modul inferensi matematika terpadu dari nol tanpa scikit-learn/PyTorch, menguji kebenaran numerik terhadap pustaka standar.",
        content_markdown: `> ⏳ **Kerangka Silabus (Segera Hadir)**\n>\n> Materi bab ini telah terdaftar dalam kurikulum resmi dan silabus pembelajaran platform Velqora, dan sedang dalam tahap penulisan terverifikasi bebas data sintetis berdasarkan rujukan literatur akademik standar.`,
        contentStatus: "legacy-synthetic",
        reviewStatus: "legacy_synthetic",
      },
    ],
  },
];

export const matematikaStatistikaCurriculum: AcademicCurriculum = {
  id: "matematika-statistika-untuk-ai",
  slug: "matematika-statistika-untuk-ai",
  title: "Matematika & Statistika untuk AI",
  category: "Kecerdasan Buatan",
  level: "pemula",
  description: "Fondasi matematika analitis, aljabar linier komputasional, kalkulus multivariat matriks, teori probabilitas aksiomatik, estimasi parameter MLE & MAP, dekomposisi bias-variance teori belajar statistik, serta optimasi numerik cembung (Convex Optimization) untuk machine learning dan AI.",
  estimatedHours: 85,
  version: "1.0.0",
  auditStatus: "VERIFIED",
  primaryReferences: [
    {
      id: "src-math-esl",
      title: "The Elements of Statistical Learning: Data Mining, Inference, and Prediction (2nd Edition)",
      authors: ["Trevor Hastie", "Robert Tibshirani", "Jerome Friedman"],
      type: "book",
      url: "https://hastie.su.domains/ElemStatLearn/",
      sourceType: "academic-book",
      provider: "Springer",
      relevance: "Rujukan kanonikal dekomposisi bias-variance, teori belajar statistik VC-dimension, dan inferensi keteraturan data.",
      verified: true,
      lastChecked: "2026-09-20",
    },
    {
      id: "src-math-boyd",
      title: "Convex Optimization",
      authors: ["Stephen Boyd", "Lieven Vandenberghe"],
      type: "book",
      url: "https://web.stanford.edu/~boyd/cvxbook/",
      sourceType: "academic-book",
      provider: "Cambridge University Press",
      relevance: "Buku standar dunia untuk optimasi cembung, kondisi Karush-Kuhn-Tucker (KKT), metode gradien terkonjugasi, dan dualitas Lagrange.",
      verified: true,
      lastChecked: "2026-09-20",
    },
    {
      id: "src-math-murphy",
      title: "Probabilistic Machine Learning: An Introduction",
      authors: ["Kevin P. Murphy"],
      type: "book",
      url: "https://probml.github.io/pml-book/book1.html",
      sourceType: "academic-book",
      provider: "MIT Press",
      relevance: "Landasan komprehensif teori probabilitas multivariat, inferensi Bayesian, estimasi parameter MLE/MAP, dan teori informasi.",
      verified: true,
      lastChecked: "2026-09-20",
    },
  ],
  chapters: mathStatChapters,
};
