"use client";

import React from "react";
import {
  LayoutGrid,
  LayoutDashboard,
  BarChart3,
  Users,
  Layers,
  GraduationCap,
  BookOpen,
  CheckSquare,
  ClipboardList,
  Bookmark,
  PenLine,
  FileEdit,
  Bot,
  BrainCircuit,
  Sparkles,
  ScanLine,
  Scan,
  Code2,
  FolderTree,
  FolderOpen,
  FolderCode,
  Tags,
  Tag,
  Files,
  FileBox,
  FileText,
  Compass,
  HardDriveDownload,
  Download,
  ShieldCheck,
  MapPin,
  Globe,
  Sliders,
  Calendar,
} from "lucide-react";
import { TranslationKey } from "@/lib/i18n/translations";

export const iconMap: Record<string, React.ElementType> = {
  LayoutGrid,
  LayoutDashboard,
  BarChart3,
  Users,
  Layers,
  GraduationCap,
  BookOpen,
  CheckSquare,
  ClipboardList,
  Bookmark,
  PenLine,
  FileEdit,
  Bot,
  BrainCircuit,
  Sparkles,
  ScanLine,
  Scan,
  Code2,
  FolderTree,
  FolderOpen,
  FolderCode,
  Tags,
  Tag,
  Files,
  FileBox,
  FileText,
  Compass,
  HardDriveDownload,
  Download,
  ShieldCheck,
  MapPin,
  Globe,
  Sliders,
  Calendar,
};

export const categoryTitleMap: Record<string, TranslationKey> = {
  MAIN: "catMain",
  Utama: "catMain",
  PEMBELAJARAN: "catLearning",
  Pembelajaran: "catLearning",
  "AI & SMART LEARNING": "catAi",
  "Fitur AI": "catAi",
  "FITUR & ALAT": "catTools",
  "Fitur & Alat": "catTools",
  TOOLS: "catTools",
  Alat: "catTools",
  ORGANISASI: "catOrg",
  Organisasi: "catOrg",
  BANTUAN: "catHelp",
  Bantuan: "catHelp",
  PENGATURAN: "catSystem",
  Pengaturan: "catSystem",
  SYSTEM: "catSystem",
  Sistem: "catSystem",
  ADMINISTRATION: "adminPanel",
  Administrasi: "adminPanel",
  ownerPanel: "ownerPanel",
};

export const linkLabelMap: Record<string, TranslationKey> = {
  Dashboard: "navDashboard",
  "Ringkasan Pembelajaran": "navDashboard",
  "Statistik Belajar": "navStatistik",
  "Semua Modul": "navModul",
  "Modul & Project": "navModul",
  "Modul dan Project": "navModul",
  "Modul & Panduan": "navModul",
  "Koleksi Materi": "navMateri",
  "Materi Pembelajaran": "navMateri",
  "Bahan Ajar & Dokumen": "navMateri",
  "Semua Tugas": "navTugas",
  "Tugas & Jadwal": "navTugas",
  "Tugas Pembelajaran": "navTugas",
  "Materi Tersimpan": "navBookmark",
  "Catatan Belajar": "navCatatan",
  "Asisten AI": "navAiTutor",
  "AI Assistant": "navAiTutor",
  "Tutor AI": "navAiTutor",
  "AI Tutor Cerdas": "navAiTutor",
  "Latihan dan Kuis": "navKuisAi",
  "Latihan & Kuis AI": "navKuisAi",
  "Konversi Berkas": "navKonversi",
  "Konversi & OCR Berkas": "navKonversi",
  "Ruang Praktik Kode": "navPlayground",
  "Ruang Praktik & Alat": "navPlayground",
  "Kategori Pembelajaran": "navKategori",
  "Kategori & Subjek": "navKategori",
  "Label dan Tag": "navTag",
  "Label & Tag": "navTag",
  "Berkas Pembelajaran": "navFile",
  "Semua Berkas": "navFile",
  "Ruang Kelas": "navKelas",
  "Jadwal & Reminder": "navJadwal",
  "Jadwal Perkuliahan": "navJadwal",
  "Statistik & Progres": "navStatistik",
  Panduan: "navPanduan",
  "Cadangkan Data": "navBackup",
  "Cadangan Data": "navBackup",
  Pengaturan: "navPengaturan",
  "Pengaturan Workspace": "navPengaturan",
  "Kelola Role": "navKelolaRole",
  "Kelola Hak Akses": "navKelolaRole",
  "Peta Pengguna": "navTotalPengguna",
};
