"use client";

import React from "react";
import {
  LayoutGrid,
  LayoutDashboard,
  BarChart3,
  Users,
  Layers,
  GraduationCap,
  BookOpen,
  CheckSquare,
  ClipboardList,
  Bookmark,
  PenLine,
  FileEdit,
  Bot,
  BrainCircuit,
  Sparkles,
  ScanLine,
  Scan,
  Code2,
  FolderTree,
  FolderCode,
  Tags,
  Tag,
  Files,
  FileBox,
  FileText,
  Compass,
  HardDriveDownload,
  Download,
  ShieldCheck,
  MapPin,
  Globe,
  Sliders,
  Calendar,
} from "lucide-react";
import { TranslationKey } from "@/lib/i18n/translations";
import { SettingsGearIcon } from "@/components/icons/settings-gear-icon";
import { FolderPixelIcon } from "@/components/icons/folder-pixel-icon";

export const iconMap: Record<string, React.ElementType> = {
  Settings: SettingsGearIcon,
  SettingsGear: SettingsGearIcon,
  FolderPixel: FolderPixelIcon,
  PixelFolder: FolderPixelIcon,
  LayoutGrid,
  LayoutDashboard,
  BarChart3,
  Users,
  Layers,
  GraduationCap,
  BookOpen,
  CheckSquare,
  ClipboardList,
  Bookmark,
  PenLine,
  FileEdit,
  Bot,
  BrainCircuit,
  Sparkles,
  ScanLine,
  Scan,
  Code2,
  FolderTree,
  FolderOpen: FolderPixelIcon,
  FolderCode,
  Tags,
  Tag,
  Files,
  FileBox,
  FileText,
  Compass,
  HardDriveDownload,
  Download,
  ShieldCheck,
  MapPin,
  Globe,
  Sliders,
  Calendar,
};

export const categoryTitleMap: Record<string, TranslationKey> = {
  Utama: "catMain",
  MAIN: "catMain",
  Modul: "catModul",
  MODUL: "catModul",
  Project: "catProject",
  PROJECT: "catProject",
  "Alat AI": "catAi",
  "ALAT AI": "catAi",
  Sistem: "catSystem",
  SISTEM: "catSystem",
  Administrasi: "adminPanel",
  ADMINISTRATION: "adminPanel",
  ownerPanel: "ownerPanel",
};

export const linkLabelMap: Record<string, TranslationKey> = {
  Dashboard: "navDashboard",
  "Katalog Modul": "navKatalogModul",
  "Materi Pembelajaran": "navMateri",
  "Semua Berkas": "navFile",
  "Materi Tersimpan": "navBookmark",
  "Catatan Belajar": "navCatatan",
  "Repositori Project": "navProject",
  "AI Tutor Cerdas": "navAiTutor",
  "Latihan & Kuis AI": "navKuisAi",
  "Ruang Praktik Kode": "navPlayground",
  "Konversi & OCR Berkas": "navKonversi",
  "Pengaturan Umum": "navPengaturan",
  "Kategori & Subjek": "navKategori",
  "Label & Tag": "navTag",
  "Cadangan Data": "navBackup",
  Panduan: "navPanduan",
  "Pasang Aplikasi": "navPasangAplikasi",
  "Kelola Hak Akses": "navKelolaRole",
  "Peta Pengguna": "navTotalPengguna",
  "Statistik Belajar": "navStatistik",
};
