import { TopicSpec, ChapterSpec } from "./generate";
import { createChapter } from "./domains-batch1";

// 6. AUTOML & NEURAL ARCHITECTURE SEARCH (12 Bab)
export function getAutoMlSpec(): TopicSpec {
  const chapters: ChapterSpec[] = [
    createChapter(1, "Paradigma AutoML & Otomasi Siklus Hidup Machine Learning", "Ruang lingkup otomasi dari data cleaning, feature engineering, pemilihan model, hingga tuning.", ["AutoML Scope", "Pipeline Automation", "Optimization Landscapes"], [
      { title: "Definisi Formal Masalah CASH (Combined Algorithm Selection and Hyperparameter)", conceptEn: "CASH Problem Formulation", formula: "$$A^*, \\lambda^* = \\arg\\min_{A \\in \\mathcal{A}, \\lambda \\in \\Lambda_A} \\frac{1}{K} \\sum_{k=1}^K \\mathcal{L}(A_\\lambda, D_{\\text{train}}^{(k)}, D_{\\text{val}}^{(k)})$$", code: "print('CASH selects optimal algorithm A and hyperparameters lambda simultaneously')" },
      { title: "Taksonomi Spektrum Otomasi Machine Learning", conceptEn: "AutoML Spectrum", code: "spectrum = ['Data Prep', 'Feature Eng', 'Model Selection', 'Hyperparameter Tuning', 'Ensembling']\nprint(spectrum)" },
      { title: "Keterbatasan Grid Search & Kerutukan Dimensi", conceptEn: "Curse of Dimensionality in Tuning", formula: "$$\\text{Evaluations} = \\prod_{i=1}^D K_i = \\mathcal{O}(K^D)$$", code: "def grid_evals(dims, points_per_dim=5): return points_per_dim ** dims\nprint('5 dims grid count:', grid_evals(5))" },
      { title: "Efisiensi Random Search (Bergstra & Bengio, 2012)", conceptEn: "Random Search Efficiency", code: "import numpy as np\ndef random_search_sample(low, high, n=10): return np.random.uniform(low, high, n)\nprint('Random samples:', random_search_sample(0.001, 0.1, 3))" },
      { title: "Tolak Ukur Benchmark OpenML AutoML", conceptEn: "OpenML AutoML Benchmark", code: "benchmarks = ['OpenML-CC18', 'AutoML Benchmark (AMLB)']\nprint(benchmarks)" },
      { title: "Meta-Learning untuk Warm-Starting Optimasi", conceptEn: "Meta-Learning Warm Start", code: "def warm_start(dataset_metafeatures): return {'recommended_algo': 'LightGBM', 'lr': 0.05}" },
      { title: "Evaluasi Overfitting dalam Pencarian Hyperparameter", conceptEn: "Overfitting in Hyperparameter Tuning", code: "def overfit_metric(val_score, test_score): return val_score - test_score" },
      { title: "Batasan Waktu & Komputasi (Resource Budgeting)", conceptEn: "Time and Resource Budgeting", code: "budget = {'time_limit_s': 3600, 'memory_limit_gb': 16}\nprint(budget)" },
      { title: "Integrasi Human-in-the-Loop pada AutoML", conceptEn: "Interactive AutoML", code: "def human_override(param): return 'Param locked by domain expert'" },
      { title: "Arsitektur Pustaka AutoML Populer (TPOT, Auto-sklearn, FLAML)", conceptEn: "AutoML Library Landscape", code: "libraries = ['Auto-sklearn', 'TPOT', 'FLAML', 'H2O AutoML']\nprint(libraries)" },
    ]),
    createChapter(2, "Optimasi Bayesian & Model Berbasis Pengganti (Surrogate)", "Proses Gaussian, fungsi akuisisi (EI, PI, UCB), dan eksplorasi vs eksploitasi.", ["Bayesian Optimization", "Gaussian Processes", "Acquisition Functions"], [
      { title: "Formulasi Proses Gaussian sebagai Fungsi Pengganti (Surrogate)", conceptEn: "Gaussian Process Regression", formula: "$$f(x) \\sim \\mathcal{GP}(m(x), k(x, x'))$$", code: "from sklearn.gaussian_process import GaussianProcessRegressor\ngp = GaussianProcessRegressor()\nprint('GP Regressor initialized')" },
      { title: "Fungsi Kernel Kovariansi (RBF & Matérn 5/2)", conceptEn: "Matérn Covariance Kernel", formula: "$$k_{\\text{Matérn 5/2}}(r) = \\sigma^2 \\left( 1 + \\sqrt{5}r + \\frac{5}{3}r^2 \\right) \\exp(-\\sqrt{5}r)$$", code: "from sklearn.gaussian_process.kernels import Matern\nkernel = Matern(nu=2.5)\nprint('Matern 5/2 kernel ready')" },
      { title: "Fungsi Akuisisi Expected Improvement (EI)", conceptEn: "Expected Improvement (EI)", formula: "$$\\text{EI}(x) = (\\mu(x) - f(x^+) - \\xi)\\Phi(Z) + \\sigma(x)\\phi(Z)$$", code: "from scipy.stats import norm\ndef expected_improvement(mu, sigma, f_best, xi=0.01):\n    imp = mu - f_best - xi\n    Z = imp / (sigma + 1e-9)\n    return imp * norm.cdf(Z) + sigma * norm.pdf(Z)\nprint('EI value:', expected_improvement(0.85, 0.1, 0.80))" },
      { title: "Fungsi Akuisisi Probability of Improvement (PI)", conceptEn: "Probability of Improvement (PI)", formula: "$$\\text{PI}(x) = \\Phi\\left( \\frac{\\mu(x) - f(x^+) - \\xi}{\\sigma(x)} \\right)$$", code: "def prob_improvement(mu, sigma, f_best, xi=0.01): return norm.cdf((mu - f_best - xi)/(sigma + 1e-9))" },
      { title: "Upper Confidence Bound (GP-UCB)", conceptEn: "GP-UCB Acquisition", formula: "$$\\text{UCB}(x) = \\mu(x) + \\beta_t \\sigma(x)$$", code: "def gpubc(mu, sigma, beta=2.0): return mu + beta * sigma\nprint('UCB:', gpubc(0.8, 0.15))" },
      { title: "Dilema Eksplorasi vs Eksploitasi", conceptEn: "Exploration vs Exploitation Trade-off", code: "def trade_off(beta): return 'High Exploration' if beta > 3.0 else 'High Exploitation'" },
      { title: "Optimasi Batch (Batch Bayesian Optimization - q-EI)", conceptEn: "Batch Bayesian Optimization", code: "def sample_batch_candidates(q=4): return f'Selected {q} parallel evaluation points'" },
      { title: "Penanganan Variabel Kategorik & Bersyarat", conceptEn: "Categorical Bayesian Optimization", code: "print('One-hot encoding vs Tree-based surrogates for non-continuous hyperparameters')" },
      { title: "Biaya Komputasi $O(N^3)$ Proses Gaussian", conceptEn: "Cubic Complexity of GP", formula: "$$\\mathcal{O}(N^3) \\text{ inversion of } N \\times N \\text{ kernel matrix}$$", code: "print('Scalability limit: GPs slow down beyond ~1000 evaluations')" },
      { title: "Studi Kasus Penyetelan Model LightGBM dengan BoTorch", conceptEn: "BoTorch LightGBM Case", code: "print('BoTorch Bayesian optimization with PyTorch autograd gradients')" },
    ]),
    createChapter(3, "Tree-structured Parzen Estimator (TPE) & Optuna", "Pemodelan non-parametrik kernel density, arsitektur Optuna, dan studi praktis.", ["TPE Algorithm", "Optuna Framework", "Hyperparameter Search"], [
      { title: "Mekanisme Algoritma TPE (Bergstra et al.)", conceptEn: "TPE Algorithm Formulation", formula: "$$p(x \\mid y) = \\begin{cases} \\ell(x) & \\text{if } y < y^* \\\\ g(x) & \\text{if } y \\ge y^* \\end{cases}$$", code: "print('TPE models density of good vs bad configurations separately')" },
      { title: "Rasio Densitas $\\ell(x) / g(x)$ sebagai Pengganti EI", conceptEn: "TPE Density Ratio", formula: "$$\\text{EI}(x) \\propto \\frac{\\ell(x)}{g(x)}$$", code: "def tpe_score(l_x, g_x): return l_x / (g_x + 1e-9)\nprint('TPE Score:', tpe_score(0.8, 0.2))" },
      { title: "Arsitektur Framework Optuna: Study, Trial, Sampler", conceptEn: "Optuna Architecture", code: "import optuna\ndef objective(trial):\n    x = trial.suggest_float('x', -10, 10)\n    return (x - 2) ** 2\nstudy = optuna.create_study(direction='minimize')\nstudy.optimize(objective, n_trials=10)\nprint('Best trial:', study.best_value)" },
      { title: "Jenis Distribusi Saran Parameter (suggest_float, suggest_categorical)", conceptEn: "Optuna Parameter Suggestions", code: "def optuna_types(trial):\n    lr = trial.suggest_float('lr', 1e-5, 1e-1, log=True)\n    n_est = trial.suggest_int('n_est', 50, 500)\n    opt = trial.suggest_categorical('opt', ['adam', 'sgd'])\n    return lr, n_est, opt" },
      { title: "Penyimpanan Persistent Database RDB (SQLite/Postgres)", conceptEn: "Optuna RDB Storage", code: "storage = 'sqlite:///optuna_study.db'\nprint('Storage connection string:', storage)" },
      { title: "Visualisasi Optuna: Optimization History & Param Importances", conceptEn: "Optuna Visualizations", code: "vis = ['plot_optimization_history', 'plot_param_importances', 'plot_parallel_coordinate']\nprint(vis)" },
      { title: "Integrasi Optuna dengan Scikit-Learn dan PyTorch", conceptEn: "Optuna ML Integrations", code: "print('from optuna.integration import PyTorchLightningPruningCallback')" },
      { title: "Pencarian Multi-Objektif (Pareto Multi-Objective)", conceptEn: "Multi-Objective Optuna", code: "study_multi = optuna.create_study(directions=['minimize', 'minimize'])\nprint('Directions:', study_multi.directions)" },
      { title: "Hyperparameter Pruning Berbasis State Callback", conceptEn: "Optuna Trial Pruning", code: "def prune_check(trial, step, score):\n    trial.report(score, step)\n    if trial.should_prune(): raise optuna.TrialPruned()" },
      { title: "Optimasi Terdistribusi Paralel dengan Multiple Workers", conceptEn: "Distributed Optuna Tuning", code: "print('Run multiple optuna workers pointing to same PostgreSQL database URL')" },
    ]),
    createChapter(4, "Early Stopping & Successive Halving (Hyperband)", "Alokasi sumber daya adaptif untuk mempercepat pemotongan konfigurasi buruk.", ["Early Stopping", "Successive Halving", "Hyperband"], [
      { title: "Konsep Successive Halving (SHA - Jamieson & Talwalkar)", conceptEn: "Successive Halving Algorithm", formula: "$$N_{k+1} = \\lfloor N_k / \\eta \\rfloor, \\quad R_{k+1} = R_k \\times \\eta$$", code: "def sha_round(n, r, eta=3): return n // eta, r * eta\nprint('Next round (N, R):', sha_round(81, 1))" },
      { title: "Algoritma Hyperband (Li et al., 2018)", conceptEn: "Hyperband Algorithm", code: "print('Hyperband balances exploration of many configurations with deep allocation for top performers')" },
      { title: "ASHA: Asynchronous Successive Halving", conceptEn: "ASHA Algorithm", code: "print('ASHA eliminates barrier synchronization between rounds in distributed clusters')" },
      { title: "Kurva Belajar Ekstrapolasi (Learning Curve Extrapolation)", conceptEn: "Learning Curve Extrapolation", code: "def extrapolate_loss(loss_history): return loss_history[-1] - 0.05" },
      { title: "Pemberhentian Dini Berbasis Patience & Delta", conceptEn: "Patience Early Stopping", code: "def check_early_stop(history, patience=5, min_delta=1e-4):\n    best = min(history)\n    return len(history) - history.index(best) > patience\nprint('Stop check:', check_early_stop([0.5, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45]))" },
      { title: "Median Pruner pada Optuna", conceptEn: "Optuna MedianPruner", code: "pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=10)\nprint('Median pruner active')" },
      { title: "Percentile Pruner vs Threshold Pruner", conceptEn: "Percentile vs Threshold Pruner", code: "pruner = optuna.pruners.PercentilePruner(25.0)\nprint('Prunes bottom 25%')" },
      { title: "Evaluasi Trade-off Alokasi Epoch vs Jumlah Konfigurasi", conceptEn: "Budget Allocation Trade-off", code: "total_epochs = 100 * 5\nprint('Total compute budget:', total_epochs)" },
      { title: "Stabilitas Performa Model yang Dipangkas Dini", conceptEn: "Early Stopping Stability Check", code: "def ranking_correlation(): return 0.88 # Kendall tau" },
      { title: "Implementasi Hyperband dari Nol dengan Python", conceptEn: "Python Hyperband Implementation", code: "def run_hyperband_simulation(): return 'Hyperband simulation completed with 5 brackets'" },
    ]),
    createChapter(5, "Automated Feature Engineering & Seleksi Fitur", "Transformasi otomatis, sintesis fitur matematis, dan reduksi dimensi dinamis.", ["Automated Feature Engineering", "Featuretools", "Deep Feature Synthesis"], [
      { title: "Deep Feature Synthesis (DFS - Kanter & Veeramachaneni)", conceptEn: "Deep Feature Synthesis", code: "print('DFS stacks primitive functions across entity-relationship graphs')" },
      { title: "Primitif Transformasi vs Primitif Agregasi", conceptEn: "Feature Primitives", code: "primitives = {'Transform': ['log', 'diff', 'time_since'], 'Aggregate': ['mean', 'count', 'max']}\nprint(primitives)" },
      { title: "Framework Featuretools dalam Python", conceptEn: "Featuretools Usage", code: "print('import featuretools as ft; es = ft.EntitySet(id=\"data\")')" },
      { title: "Pembuatan Fitur Interaksi Polinomial Otomatis", conceptEn: "Polynomial Interactions", code: "from sklearn.preprocessing import PolynomialFeatures\npoly = PolynomialFeatures(degree=2, interaction_only=True)\nprint('Poly transformer ready')" },
      { title: "Ekstraksi Fitur Deret Waktu Otomatis (tsfresh)", conceptEn: "tsfresh Time Series Extraction", code: "print('from tsfresh import extract_features')" },
      { title: "Seleksi Fitur Otomatis Berbasis Model (Boruta & RFECV)", conceptEn: "Boruta & RFECV Selection", code: "from sklearn.feature_selection import RFECV\nfrom sklearn.ensemble import RandomForestClassifier\nselector = RFECV(RandomForestClassifier(), cv=3)\nprint('RFECV selector created')" },
      { title: "Penyaringan Multikolinieritas Otomatis (VIF Thresholding)", conceptEn: "Automated VIF Pruning", formula: "$$\\text{VIF}_i = \\frac{1}{1 - R_i^2}$$", code: "def vif_filter(vif_scores, thresh=10.0): return [col for col, v in vif_scores.items() if v < thresh]" },
      { title: "Deteksi dan Penanganan Otomatis Outlier & Missing Values", conceptEn: "Automated Imputation", code: "from sklearn.impute import SimpleImputer\nimp = SimpleImputer(strategy='median')\nprint('Imputer ready')" },
      { title: "Pencegahan Kebocoran Fitur dalam Feature Engineering Otomatis", conceptEn: "Feature Leakage Prevention", code: "def check_leakage(engineered_cols, target_col): return target_col not in engineered_cols" },
      { title: "Evaluasi Peningkatan Metrik Model dari Fitur Sintetis", conceptEn: "Feature Gain Evaluation", code: "score_before = 0.81; score_after = 0.86\nprint('Delta AUC:', score_after - score_before)" },
    ]),
    createChapter(6, "Ruang Pencarian NAS (Neural Architecture Search Space)", "Mendefinisikan ruang arsitektur sel, graf DAG mikro vs makro.", ["NAS Search Space", "Cell-based Search", "Micro vs Macro Search"], [
      { title: "Taksonomi Ruang Pencarian NAS (Elsken et al., 2019)", conceptEn: "NAS Search Space Taxonomy", code: "spaces = ['Macro search space', 'Cell-based (micro) search space', 'Hierarchical space']\nprint(spaces)" },
      { title: "Ruang Pencarian Berbasis Sel (Cell-based: Normal & Reduction Cell)", conceptEn: "Cell-Based NAS", code: "cells = {'Normal Cell': 'Preserves spatial dimensions', 'Reduction Cell': 'Halves spatial dimensions, doubles channels'}\nprint(cells)" },
      { title: "Representasi Directed Acyclic Graph (DAG) Sel Jaringan", conceptEn: "DAG Cell Representation", code: "dag = {'node_0': ['input_1', 'input_2'], 'node_1': [('node_0', 'conv_3x3')]}\nprint('DAG nodes:', len(dag))" },
      { title: "Himpunan Operasi Kandidat (Operations Pool)", conceptEn: "Operations Pool", code: "ops = ['conv_3x3', 'conv_5x5', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'zero']\nprint('Operations count:', len(ops))" },
      { title: "Ruang Pencarian Macro (Pencarian Topologi Global)", conceptEn: "Macro Search Space", code: "print('Macro space searches layer connections from input to output directly')" },
      { title: "Ruang Pencarian Hardware-Aware (OFA - Once-for-All)", conceptEn: "Hardware-Aware Search Space", code: "subnets = {'depth': [2, 3, 4], 'width_mult': [0.5, 0.75, 1.0], 'kernel': [3, 5, 7]}\nprint(subnets)" },
      { title: "Ruang Pencarian NAS-Bench-101 dan NAS-Bench-201", conceptEn: "NAS Benchmark Spaces", code: "bench = {'NAS-Bench-101': '423k models evaluated', 'NAS-Bench-201': 'Fixed 4-node cell space'}\nprint(bench)" },
      { title: "Ukuran Kombinatorial Ruang Pencarian", conceptEn: "Combinatorial Space Complexity", formula: "$$|\\mathcal{S}| = \\prod_{i=1}^{N_{\\text{nodes}}} \\left( \\binom{i}{2} \\times |\\mathcal{O}|^2 \\right) \\approx 10^{18}$$", code: "print('Combinatorial explosion makes exhaustive search intractable')" },
      { title: "Validasi Konektivitas dan Kelayakan Graf Arsitektur", conceptEn: "Architecture Validity Check", code: "def is_valid_dag(edges): return 'Acyclic validated'" },
      { title: "Visualisasi Struktur Arsitektur Hasil Pencarian", conceptEn: "Architecture Graph Visualization", code: "print('Render DAG using NetworkX and Graphviz')" },
    ]),
    createChapter(7, "Strategi Evaluasi Kinerja Arsitektur NAS", "Akselerasi evaluasi: estimasi performa, weight inheritance, dan surrogate.", ["Performance Estimation", "Weight Inheritance", "Zero-Cost Proxies"], [
      { title: "Metode Evaluasi Standar: Pelatihan Penuh vs Biaya Komputasi", conceptEn: "Full Training Baseline", code: "cost = 800 * 24 # 800 GPUs for 24 days in original Zoph et al. NAS\nprint('GPU hours:', cost)" },
      { title: "Pelatihan dengan Resolusi/Epoch Lebih Rendah (Fidelity)", conceptEn: "Lower Fidelity Estimation", code: "def downsample_fidelity(img_size=16, epochs=5): return 'Proxy evaluation'" },
      { title: "Kurva Belajar Perkiraan Awal (Learning Curve Extrapolation)", conceptEn: "Early Learning Curve Prediction", code: "def predict_final_acc(acc_epoch_5): return acc_epoch_5 + 0.15" },
      { title: "Weight Inheritance & Network Morphism", conceptEn: "Network Morphism", code: "print('Function-preserving transformations: add layer while keeping same output initially')" },
      { title: "Model Pengganti Prediksi Performa (Performance Surrogates)", conceptEn: "Performance Predictor Models", code: "from sklearn.ensemble import GradientBoostingRegressor\npredictor = GradientBoostingRegressor()\nprint('Predicts validation accuracy from graph adjacency matrix')" },
      { title: "Zero-Cost Proxies (SynFlow, snip, grad_norm)", conceptEn: "Zero-Cost NAS Proxies", formula: "$$\\mathcal{R}_{\\text{SynFlow}} = \\sum_{l=1}^L \\mathbf{1}^T \\left| \\frac{\\partial \\mathcal{R}}{\\partial \\theta_l} \\odot \\theta_l \\right| \\mathbf{1}$$", code: "def synflow_score(params, grads): return sum(abs(p * g).sum() for p, g in zip(params, grads))" },
      { title: "Korelasi Ranking Zero-Cost Proxies (Spearman rho)", conceptEn: "Proxy Rank Correlation", formula: "$$\\rho = 1 - \\frac{6 \\sum d_i^2}{n(n^2 - 1)}$$", code: "from scipy.stats import spearmanr\nprint('Spearman correlation:', spearmanr([1, 2, 3], [1, 3, 2]).statistic)" },
      { title: "Estimasi Latensi Perangkat Keras Nyata (Hardware LUT)", conceptEn: "Hardware Latency Look-up Table", code: "lut = {'conv3x3_c64': 1.2, 'conv5x5_c64': 2.5} # ms\nprint('Latensi conv3x3:', lut['conv3x3_c64'])" },
      { title: "Evaluasi Ketahanan Arsitektur terhadap Derau", conceptEn: "Architecture Robustness Evaluation", code: "def test_adversarial_transfer(): return 'Evaluated on FGSM test set'" },
      { title: "Sintesis Trade-off Akurasi, Latensi, dan FLOPs", conceptEn: "Multi-Objective Performance Synthesis", code: "score = 0.8 * 0.85 - 0.2 * (4.5 / 10.0)\nprint('Composite metric:', score)" },
    ]),
    createChapter(8, "One-Shot NAS & Differentiable NAS (DARTS)", "Pencarian arsitektur terdiferensialkan berbasis gradien kontinu.", ["One-Shot NAS", "DARTS", "Continuous Relaxation"], [
      { title: "Supernet & Konsep Bobot Bersama (Weight Sharing)", conceptEn: "Supernet Weight Sharing", code: "print('One single supernet subsumes all possible architectures in search space')" },
      { title: "Relaksasi Kontinu Ruang Operasi (DARTS - Liu et al.)", conceptEn: "Continuous Relaxation Formulation", formula: "$$\\bar{o}^{(i, j)}(x) = \\sum_{o \\in \\mathcal{O}} \\frac{\\exp(\\alpha_o^{(i, j)})}{\\sum_{o' \\in \\mathcal{O}} \\exp(\\alpha_{o'}^{(i, j)})} o(x)$$", code: "import numpy as np\ndef softmax_weights(alpha):\n    e = np.exp(alpha - np.max(alpha))\n    return e / e.sum()\nprint('Softmax arch weights:', softmax_weights([1.2, 0.5, 2.1]))" },
      { title: "Optimasi Bilevel pada DARTS", conceptEn: "Bilevel Optimization in DARTS", formula: "$$\\min_\\alpha \\mathcal{L}_{\\text{val}}(w^*(\\alpha), \\alpha) \\quad \\text{s.t.} \\quad w^*(\\alpha) = \\arg\\min_w \\mathcal{L}_{\\text{train}}(w, \\alpha)$$", code: "print('Alternating gradient updates for model weights w and architecture params alpha')" },
      { title: "Aproksimasi Gradien Orde Pertama vs Orde Kedua", conceptEn: "First-Order vs Second-Order DARTS", code: "print('First-order DARTS assumes w*(alpha) ~ w without unrolling virtual gradient steps')" },
      { title: "Discretization Gap & Masalah Performance Collapse", conceptEn: "DARTS Performance Collapse", code: "def collapse_check(weights):\n    return 'Warning: Parameterless ops (skip-connect) dominating' if weights['skip'] > 0.8 else 'Healthy'" },
      { title: "Regularisasi Pencegahan Dominansi Skip-Connection (P-DARTS)", conceptEn: "P-DARTS & Robust DARTS", code: "print('P-DARTS progressively increases search depth to bridge depth gap')" },
      { title: "Single-Path One-Shot (SPOS - Guo et al.)", conceptEn: "Single-Path One-Shot NAS", code: "def sample_random_path(supernet): return 'Sample uniform single subnet per step'" },
      { title: "FairNAS: Evaluasi Subnet yang Adil Tanpa Co-adaptation", conceptEn: "FairNAS Paradigm", code: "print('FairNAS enforces strictly equal training opportunities for all candidates')" },
      { title: "Ekstraksi Arsitektur Diskrit Akhir dari Supernet", conceptEn: "Discrete Architecture Derivation", code: "def derive_arch(alphas): return [np.argmax(a) for a in alphas]" },
      { title: "Retraining Mandiri Arsitektur Hasil DARTS", conceptEn: "Stand-alone Architecture Retraining", code: "print('Retrain derived architecture from scratch with cosine annealing and CutMix')" },
    ]),
    createChapter(9, "Hardware-Aware NAS (HW-NAS) & Edge Optimization", "Optimasi arsitektur terikat memori, daya, dan latensi mikrokontroler.", ["Hardware-Aware NAS", "Edge AI Optimization", "Once-for-All"], [
      { title: "Motivasi Hardware-Aware NAS untuk Perangkat Edge", conceptEn: "HW-NAS Motivation", code: "constraints = {'Max RAM': '256 KB', 'Max Flash': '1 MB', 'Latency': '<50ms'}\nprint(constraints)" },
      { title: "Model Biaya Latensi: Profiling Langsung vs Tabel Lookup (LUT)", conceptEn: "Latency Lookup Tables", code: "lut = {'C3_64': 0.8, 'C5_64': 1.9, 'DW3_64': 0.3}\nprint('Total latency:', lut['C3_64'] + lut['DW3_64'])" },
      { title: "Arsitektur ProxylessNAS (Cai et al., 2019)", conceptEn: "ProxylessNAS Architecture", code: "print('ProxylessNAS binarizes architecture parameters to directly optimize on GPU/Mobile memory')" },
      { title: "Model Kerugian Multi-Objektif Berbobot Latensi", conceptEn: "Latency-Constrained Loss", formula: "$$\\mathcal{L}_{\\text{total}} = \\mathcal{L}_{\\text{CE}} + \\lambda \\cdot \\log\\left( \\frac{\\text{Lat}}{\\text{Lat}_{\\text{target}}} \\right)$$", code: "def hw_loss(ce, lat, target=20.0, lam=0.1):\n    return ce + lam * np.log(lat / target)\nprint('HW Loss:', hw_loss(0.4, 25.0))" },
      { title: "Pendekatan Once-for-All (OFA - Han et al.)", conceptEn: "Once-for-All (OFA) Network", code: "print('Train once, deploy anywhere: Supports 10^19 subnets without retraining')" },
      { title: "Progressive Shrinking pada OFA", conceptEn: "Progressive Shrinking Strategy", code: "stages = ['Full net', 'Shrink kernel sizes', 'Shrink depth', 'Shrink width']\nprint(stages)" },
      { title: "MCUNet: TinyML NAS untuk Mikrokontroler Cortex-M", conceptEn: "MCUNet TinyML Architecture", code: "mcunet = {'Peak SRAM': '248 KB', 'Accuracy ImageNet': '70.7%'}\nprint(mcunet)" },
      { title: "Kuantisasi-Sadar Arsitektur (Joint NAS and Quantization)", conceptEn: "Joint NAS & Quantization", code: "def mixed_precision_search(): return 'Layer 1: INT8, Layer 2: INT4, Layer 3: INT8'" },
      { title: "Evaluasi Konsumsi Daya Energi (Joules per Inference)", conceptEn: "Energy Consumption Metric", formula: "$$E = P \\times t = \\text{Watts} \\times \\text{Seconds}$$", code: "def energy_mj(watts, time_s): return watts * time_s * 1000\nprint('Energy mJ:', energy_mj(1.5, 0.02))" },
      { title: "Deployment Subnet Terpilih ke Perangkat Mobile (TFLite/ONNX)", conceptEn: "Mobile Edge Deployment", code: "print('Export chosen subnet to TFLite flatbuffer for Android NNAPI')" },
    ]),
    createChapter(10, "Ensemble Otomatis & Pasca-Pemrosesan AutoML", "Stilasi model, stacking otomatis, Caruana ensemble selection, dan kalibrasi.", ["Ensemble Selection", "Model Stacking", "Caruana Algorithm"], [
      { title: "Prinsip Caruana Ensemble Selection", conceptEn: "Caruana Ensemble Selection", code: "def caruana_ensemble(models, val_preds, y_val, iters=10):\n    ensemble = []\n    for _ in range(iters):\n        best_m = models[0] # Greedy addition with replacement\n        ensemble.append(best_m)\n    return ensemble\nprint('Caruana ensemble initialized')" },
      { title: "Stacking Otomatis Multilapis (Multi-layer Stacking)", conceptEn: "Automated Multi-Layer Stacking", code: "layers = {'L1': ['XGB', 'CatBoost', 'ExtraTrees'], 'L2': ['NeuralNet', 'Ridge'], 'L3': 'Weighted Average'}\nprint(layers)" },
      { title: "Out-of-Fold (OOF) Prediction Generation", conceptEn: "OOF Prediction Pipeline", code: "def oof_predictions(n_samples): return np.zeros(n_samples)" },
      { title: "Optimasi Bobot Voting Ensemble Menggunakan Nelder-Mead", conceptEn: "Voting Weight Optimization", formula: "$$\\min_w \\mathcal{L}\\left( \\sum_{m=1}^M w_m \\hat{y}_m, y \\right) \\quad \\text{s.t.} \\quad \\sum w_m = 1, \\ w_m \\ge 0$$", code: "from scipy.optimize import minimize\ndef loss_fn(w): return sum((w - 0.2)**2)\nres = minimize(loss_fn, [0.25, 0.25, 0.25, 0.25])\nprint('Optimal weights:', res.x)" },
      { title: "Kalibrasi Probabilitas Otomatis (Platt Scaling & Isotonic)", conceptEn: "Automated Probability Calibration", code: "from sklearn.calibration import CalibratedClassifierCV\nprint('CalibratedClassifierCV ready')" },
      { title: "Distilasi Ensemble Menjadi Model Tunggal Cepat", conceptEn: "Ensemble Distillation", code: "def distill(ensemble, student, X): return 'Train student on soft probabilities of ensemble'" },
      { title: "Penyusutan Ukuran Ensembel (Ensemble Pruning)", conceptEn: "Ensemble Pruning", code: "def prune_ensemble(models, weights, thresh=0.02):\n    return [m for m, w in zip(models, weights) if w > thresh]" },
      { title: "Evaluasi Brier Score dan Log Loss Ensembel", conceptEn: "Brier Score Evaluation", formula: "$$\\text{BS} = \\frac{1}{N} \\sum_{i=1}^N (p_i - y_i)^2$$", code: "def brier_score(y_true, y_prob): return np.mean((y_true - y_prob)**2)\nprint('Brier score:', brier_score(np.array([1, 0]), np.array([0.9, 0.1])))" },
      { title: "Pencegahan Overfitting Ensembel pada Data Validasi", conceptEn: "Ensemble Overfitting Prevention", code: "def check_ensemble_overfit(train_loss, val_loss): return val_loss - train_loss" },
      { title: "Ekspor Model Ensembel ke Format Serialisasi", conceptEn: "Ensemble Serialization", code: "import joblib\nprint('joblib.dump(ensemble, \"automl_ensemble.pkl\")')" },
    ]),
    createChapter(11, "Platform AutoML Industri & Pipeline Cloud", "Implementasi pada Azure AutoML, AWS SageMaker Autopilot, dan Google Vertex AI.", ["Enterprise AutoML", "Cloud AI Pipelines", "Production AutoML"], [
      { title: "Arsitektur Enterprise AutoML: Serverless Compute & Scalability", conceptEn: "Enterprise AutoML Architecture", code: "platform = {'compute': 'Serverless GPU cluster', 'orchestration': 'Kubeflow', 'tracking': 'MLflow'}\nprint(platform)" },
      { title: "AWS SageMaker Autopilot: Modus Ensembling vs HPO", conceptEn: "SageMaker Autopilot", code: "modes = ['ENSEMBLING (AutoGluon-powered)', 'HYPERPARAMETER_TUNING (Bayesian)']\nprint(modes)" },
      { title: "Google Cloud Vertex AI Tabular AutoML", conceptEn: "Vertex AI Tabular", code: "print('Vertex AI uses neural architecture search specifically designed for tabular features')" },
      { title: "Azure Machine Learning Automated ML", conceptEn: "Azure Automated ML", code: "print('Azure AutoML handles cross-validation, guardrail checks, and explainability natively')" },
      { title: "Open-Source Enterprise: AutoGluon (Erickson et al.)", conceptEn: "AutoGluon Framework", code: "print('from autogluon.tabular import TabularPredictor; predictor = TabularPredictor(label=\"target\").fit(train_data)')" },
      { title: "Pipeline CI/CD Retraining Otomatis Berbasis Trigger", conceptEn: "Automated Retraining CI/CD", code: "trigger = {'event': 'Model performance drop > 5%', 'action': 'Trigger AutoML run'}\nprint(trigger)" },
      { title: "Monitoring Drift pada Model yang Dihasilkan AutoML", conceptEn: "AutoML Drift Monitoring", code: "def check_drift(p_val, threshold=0.05): return p_val < threshold" },
      { title: "Transparansi dan Kepatuhan Regulasi pada AutoML Cloud", conceptEn: "Regulatory Compliance in AutoML", code: "compliance = {'model_leaderboard_logged': True, 'audit_report_generated': True}\nprint(compliance)" },
      { title: "Analisis Biaya Operasional (FinOps) Pelatihan AutoML", conceptEn: "FinOps Cost Optimization", code: "cost_hpo = 50 * 2.5 # 50 GPU hours at $2.5/hr\nprint('Total Cost USD:', cost_hpo)" },
      { title: "Perbandingan Komparatif Platform AutoML Terkemuka", conceptEn: "AutoML Platform Benchmarking", code: "comparison = {'AutoGluon': 'Highest accuracy', 'FLAML': 'Fastest convergence', 'Auto-sklearn': 'Best research baselines'}\nprint(comparison)" },
    ]),
    createChapter(12, "Proyek Terintegrasi: Pembangunan Pipeline AutoML Mandiri", "Membangun sistem AutoML kustom lengkap dari nol menggunakan Python.", ["AutoML Capstone Project", "End-to-End AutoML Engine", "Pipeline Builder"], [
      { title: "Perancangan Spesifikasi Arsitektur Mesin AutoML", conceptEn: "AutoML Engine Design", code: "class MiniAutoML:\n    def __init__(self, time_budget=300): self.time_budget = time_budget\nprint('MiniAutoML initialized')" },
      { title: "Modul Pembersihan dan Deteksi Tipe Data Otomatis", conceptEn: "Automated Data Ingestion", code: "def detect_col_types(df):\n    return {'num': df.select_dtypes(include=np.number).columns.tolist(), 'cat': df.select_dtypes(include='object').columns.tolist()}\nprint('Ingestion ready')" },
      { title: "Modul Transformasi & Enkoding Fitur Otomatis", conceptEn: "Automated Feature Pipeline", code: "from sklearn.pipeline import Pipeline\nprint('Constructing dynamic ColumnTransformer pipeline')" },
      { title: "Mesin Evaluator Algoritma Kandidat Cepat (Fast Baseline)", conceptEn: "Baseline Algorithm Screening", code: "baselines = ['Dummy', 'RidgeClassifier', 'DecisionTree']\nprint('Fast baselines:', baselines)" },
      { title: "Integrasi Mesin Optimasi Bayesian Optuna Kustom", conceptEn: "Custom Optuna Optimization Engine", code: "def run_optuna_search(): return 'Best params discovered via TPE sampler'" },
      { title: "Penerapan Early Stopping dan Pruning", conceptEn: "Automated Pruning Hook", code: "def pruning_hook(score, step): return score < 0.5" },
      { title: "Konstruksi Papan Peringkat Model (Leaderboard)", conceptEn: "Leaderboard Generation", code: "leaderboard = [{'rank': 1, 'model': 'LightGBM_Tuned', 'score': 0.892}]\nprint('Leaderboard:', leaderboard)" },
      { title: "Pembentukan Ensembel Caruana Pasca-Pencarian", conceptEn: "Ensemble Aggregation Phase", code: "def build_final_ensemble(leaderboard): return 'Ensemble of Top 3 models'" },
      { title: "Generasi Laporan Penjelasan Model (XAI SHAP Automatis)", conceptEn: "Automated XAI Report", code: "def generate_shap_report(): return 'Feature importance bar chart exported'" },
      { title: "Serialisasi Artefak dan Uji Inferensi Produksi", conceptEn: "Production Artifact Release", code: "release = {'artifact': 'automl_model.bin', 'latency_ms': 12, 'status': 'VERIFIED'}\nprint(release)" },
    ]),
  ];

  return {
    file: "06-automl-nas.ts",
    exportVar: "autoMlNasCurriculum",
    id: "automl-nas",
    slug: "automl-neural-architecture-search",
    title: "AutoML & Neural Architecture Search",
    category: "Kecerdasan Buatan",
    level: "lanjutan",
    desc: "Otomasi siklus hidup machine learning dan perancangan arsitektur jaringan syaraf tiruan: formulasi masalah CASH, optimasi Bayesian, Tree-structured Parzen Estimator (TPE), Optuna, Hyperband, feature engineering otomatis, One-Shot NAS, DARTS, Hardware-Aware NAS, dan ensembling otomatis.",
    hours: 64,
    version: "2.5.0",
    sourceKeys: ["openml-repo", "sklearn-docs", "pytorch-docs", "python-docs"],
    datasetKeys: ["california-housing", "iris-flowers"],
    chapters,
  };
}
