import { AcademicCitation } from "../../src/lib/curriculum/types";

export interface VerifiedSourceItem extends AcademicCitation {
  id: string;
}

export const VERIFIED_SOURCES_CATALOG: Record<string, VerifiedSourceItem> = {
  // Python & Scientific Computing
  "python-docs": {
    id: "python-docs",
    title: "The Python Standard Library Documentation",
    authors: ["Python Software Foundation"],
    type: "documentation",
    url: "https://docs.python.org/3/",
    sourceType: "official-documentation",
    provider: "Python Software Foundation",
    relatedTopics: ["Python", "AI Fundamentals", "Data Science", "Machine Learning"],
    relatedConcepts: ["standard library", "built-in types", "control flow", "io"],
    relevance: "Dokumentasi resmi bahasa pemrograman Python 3 sebagai pondasi eksekusi seluruh pustaka AI/ML.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "python-tutorial": {
    id: "python-tutorial",
    title: "The Python Tutorial",
    authors: ["Guido van Rossum", "Python Software Foundation"],
    type: "documentation",
    url: "https://docs.python.org/3/tutorial/",
    sourceType: "official-documentation",
    provider: "Python Software Foundation",
    relatedTopics: ["Python", "Programming"],
    relatedConcepts: ["data structures", "modules", "classes", "exceptions"],
    relevance: "Panduan komprehensif sintaks dasar, struktur data bawaan, dan paradigma OOP Python.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "numpy-docs": {
    id: "numpy-docs",
    title: "NumPy Documentation & API Reference",
    authors: ["NumPy Developers"],
    type: "documentation",
    url: "https://numpy.org/doc/stable/",
    sourceType: "official-documentation",
    provider: "NumPy Community",
    relatedTopics: ["Data Science", "Machine Learning", "Deep Learning", "Computational Intelligence"],
    relatedConcepts: ["ndarray", "broadcasting", "vectorization", "linear algebra"],
    relevance: "Dokumentasi resmi komputasi array multidimensi teroptimasi C untuk sains data dan AI.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "numpy-user-guide": {
    id: "numpy-user-guide",
    title: "NumPy User Guide",
    authors: ["NumPy Developers"],
    type: "documentation",
    url: "https://numpy.org/doc/stable/user/",
    sourceType: "official-documentation",
    provider: "NumPy Community",
    relatedTopics: ["Data Science", "Linear Algebra"],
    relatedConcepts: ["indexing", "slicing", "ufuncs", "strides"],
    relevance: "Panduan lengkap penggunaan NumPy untuk manipulasi tensor dan aljabar linier numerik.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "scipy-docs": {
    id: "scipy-docs",
    title: "SciPy Reference Guide",
    authors: ["SciPy Community"],
    type: "documentation",
    url: "https://docs.scipy.org/doc/scipy/",
    sourceType: "official-documentation",
    provider: "SciPy Community",
    relatedTopics: ["Data Science", "Statistics", "Optimization"],
    relatedConcepts: ["scipy.stats", "scipy.optimize", "scipy.linalg", "hypothesis testing"],
    relevance: "Dokumentasi algoritma komputasi ilmiah: uji statistik, optimasi numerik, dan integrasi diferensial.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "pandas-docs": {
    id: "pandas-docs",
    title: "pandas Documentation & API Reference",
    authors: ["The pandas development team"],
    type: "documentation",
    url: "https://pandas.pydata.org/docs/",
    sourceType: "official-documentation",
    provider: "PyData",
    relatedTopics: ["Data Analyst", "Data Science", "Data Engineering & Big Data untuk AI"],
    relatedConcepts: ["DataFrame", "Series", "EDA", "data wrangling", "indexing"],
    relevance: "Dokumentasi resmi pustaka manipulasi data tabular, agregasi, pembersihan, dan analisis deret waktu.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "pandas-user-guide": {
    id: "pandas-user-guide",
    title: "pandas User Guide: Essential Basic Functionality",
    authors: ["The pandas development team"],
    type: "documentation",
    url: "https://pandas.pydata.org/docs/user_guide/",
    sourceType: "official-documentation",
    provider: "PyData",
    relatedTopics: ["Data Analyst", "Data Science"],
    relatedConcepts: ["merge", "concat", "groupby", "missing values", "pivot tables"],
    relevance: "Petunjuk implementasi mendalam manajemen missing data, transformasi baris-kolom, dan operasi multi-index.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "matplotlib-docs": {
    id: "matplotlib-docs",
    title: "Matplotlib: Visualization with Python",
    authors: ["Matplotlib Development Team"],
    type: "documentation",
    url: "https://matplotlib.org/stable/",
    sourceType: "official-documentation",
    provider: "Matplotlib",
    relatedTopics: ["Data Analyst", "Data Science", "Machine Learning"],
    relatedConcepts: ["figure", "axes", "scatter plot", "histogram", "visualization"],
    relevance: "Dokumentasi resmi grafik statis dan interaktif untuk eksplorasi visual data saintifik.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "seaborn-docs": {
    id: "seaborn-docs",
    title: "Seaborn: Statistical Data Visualization",
    authors: ["Michael Waskom"],
    type: "documentation",
    url: "https://seaborn.pydata.org/",
    sourceType: "official-documentation",
    provider: "Seaborn",
    relatedTopics: ["Data Analyst", "Data Science"],
    relatedConcepts: ["pairplot", "heatmap", "boxplot", "statistical visualization"],
    relevance: "Dokumentasi pembuatan visualisasi statistik inferensial berbasis matplotlib dan pandas.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Classical Machine Learning (Scikit-Learn)
  "sklearn-docs": {
    id: "sklearn-docs",
    title: "scikit-learn: Machine Learning in Python",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Science"],
    relatedConcepts: ["estimator API", "transformer", "predictor", "pipeline"],
    relevance: "Dokumentasi resmi arsitektur antarmuka pemodelan machine learning standar industri.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-user-guide": {
    id: "sklearn-user-guide",
    title: "scikit-learn User Guide: Supervised, Unsupervised & Model Selection",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/user_guide/",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning"],
    relatedConcepts: ["algorithms", "loss functions", "hyperparameters"],
    relevance: "Panduan ensiklopedis algoritma ML klasik, perumusan formulasi matematis, dan kompleksitas komputasi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-cross-validation": {
    id: "sklearn-cross-validation",
    title: "Cross-validation: evaluating estimator performance",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/modules/cross_validation.html",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Science", "Model Selection"],
    relatedConcepts: ["generalization", "train-test split", "k-fold", "stratified k-fold"],
    relevance: "Menjelaskan protokol evaluasi estimator pada data terpisah guna mengukur generalisasi dan mencegah overfitting.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-learning-curve": {
    id: "sklearn-learning-curve",
    title: "Validation curves: plotting scores to evaluate models",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/modules/learning_curve.html",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Overfitting"],
    relatedConcepts: ["learning curve", "validation curve", "bias-variance tradeoff"],
    relevance: "Panduan resmi visualisasi kurva galat latih vs validasi untuk mendeteksi underfitting dan overfitting.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-common-pitfalls": {
    id: "sklearn-common-pitfalls",
    title: "Common pitfalls and recommended practices",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/common_pitfalls.html",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Science", "MLOps"],
    relatedConcepts: ["data leakage", "evaluating on train data", "imbalance", "target leakage"],
    relevance: "Dokumentasi kesalahan fatal yang sering dialami praktisi: data leakage, evaluasi tidak representatif, dan asumsi linear salah.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-preprocessing": {
    id: "sklearn-preprocessing",
    title: "Preprocessing data",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/modules/preprocessing.html",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Preparation"],
    relatedConcepts: ["StandardScaler", "MinMaxScaler", "OneHotEncoder", "OrdinalEncoder"],
    relevance: "Standar industri transformasi fitur kategorik dan penskalaan numerik tanpa membocorkan distribusi data uji.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-pipeline": {
    id: "sklearn-pipeline",
    title: "Pipelines and composite estimators",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/modules/compose.html",
    sourceType: "official-documentation",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "MLOps & AI Deployment"],
    relatedConcepts: ["Pipeline", "ColumnTransformer", "FeatureUnion"],
    relevance: "Arsitektur perangkaian preprocessing dan pemodelan dalam satu objek estimator yang atomik dan bebas kebocoran data.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-paper": {
    id: "sklearn-paper",
    title: "Scikit-learn: Machine Learning in Python",
    authors: ["Fabian Pedregosa", "Gaël Varoquaux", "Alexandre Gramfort", "Vincent Michel", "Bertrand Thirion", "Olivier Grisel"],
    type: "paper",
    url: "https://arxiv.org/abs/1201.0490",
    doi: "10.48550/arXiv.1201.0490",
    sourceType: "paper",
    provider: "Journal of Machine Learning Research (JMLR)",
    relatedTopics: ["Machine Learning"],
    relatedConcepts: ["API design", "Python bindings", "BSD license"],
    relevance: "Paper akademik resmi pendirian pustaka scikit-learn dan prinsip desain API konsisten fit-transform-predict.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Deep Learning & Neural Networks
  "pytorch-docs": {
    id: "pytorch-docs",
    title: "PyTorch Documentation & Core API",
    authors: ["PyTorch Core Team"],
    type: "documentation",
    url: "https://pytorch.org/docs/stable/",
    sourceType: "official-documentation",
    provider: "PyTorch Foundation",
    relatedTopics: ["Deep Learning", "Computer Vision", "Natural Language Processing", "Generative AI"],
    relatedConcepts: ["torch.Tensor", "autograd", "nn.Module", "DataLoader"],
    relevance: "Dokumentasi pustaka komputasi tensor dinamis dengan diferensiasi otomatis (autograd) standar riset dan produksi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "pytorch-tutorials": {
    id: "pytorch-tutorials",
    title: "Official PyTorch Tutorials",
    authors: ["PyTorch Core Team"],
    type: "course",
    url: "https://pytorch.org/tutorials/",
    sourceType: "official-documentation",
    provider: "PyTorch Foundation",
    relatedTopics: ["Deep Learning", "Reinforcement Learning"],
    relatedConcepts: ["training loop", "loss backward", "optimizer step"],
    relevance: "Panduan implementasi resmi alur pelatihan jaringan syaraf tiruan, transfer learning, dan pemodelan sekuensial.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "deeplearning-book": {
    id: "deeplearning-book",
    title: "Deep Learning (Adaptive Computation and Machine Learning series)",
    authors: ["Ian Goodfellow", "Yoshua Bengio", "Aaron Courville"],
    type: "book",
    url: "https://www.deeplearningbook.org/",
    sourceType: "academic-book",
    provider: "MIT Press",
    relatedTopics: ["Deep Learning", "Machine Learning"],
    relatedConcepts: ["backpropagation", "convolution", "regularization", "autoencoders"],
    relevance: "Buku teks rujukan standar de facto untuk teori matematika, aljabar linier, dan optimasi jaringan syaraf tiruan.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "d2l-ai": {
    id: "d2l-ai",
    title: "Dive into Deep Learning",
    authors: ["Aston Zhang", "Zack C. Lipton", "Mu Li", "Alexander J. Smola"],
    type: "book",
    url: "https://d2l.ai/",
    sourceType: "academic-book",
    provider: "Cambridge University Press",
    relatedTopics: ["Deep Learning", "Computer Vision", "Natural Language Processing"],
    relatedConcepts: ["interactive notebooks", "modern architectures", "attention mechanism"],
    relevance: "Buku ajar universitas interaktif yang menggabungkan perumusan matematika, kode Python runnable, dan visualisasi arsitektur.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "stanford-cs231n": {
    id: "stanford-cs231n",
    title: "Stanford CS231n: Deep Learning for Computer Vision",
    authors: ["Fei-Fei Li", "Yunzhu Li", "Ruohan Gao"],
    type: "course",
    url: "https://cs231n.stanford.edu/",
    sourceType: "university-course",
    provider: "Stanford University",
    relatedTopics: ["Computer Vision", "Deep Learning"],
    relatedConcepts: ["CNN", "image classification", "object detection", "segmentation"],
    relevance: "Silabus perkuliahan standar dunia mengenai konvolusi visual, pooling, transfer learning, dan arsitektur visual modern.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "stanford-cs224n": {
    id: "stanford-cs224n",
    title: "Stanford CS224N: Natural Language Processing with Deep Learning",
    authors: ["Christopher Manning"],
    type: "course",
    url: "https://web.stanford.edu/class/cs224n/",
    sourceType: "university-course",
    provider: "Stanford University",
    relatedTopics: ["Natural Language Processing", "Large Language Model"],
    relatedConcepts: ["word embeddings", "recurrent models", "self-attention", "Transformers"],
    relevance: "Silabus universitas rujukan global untuk pemodelan bahasa, vektorisasi semantik teks, dan arsitektur Transformer.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "jurafsky-slp3": {
    id: "jurafsky-slp3",
    title: "Speech and Language Processing (3rd ed. draft)",
    authors: ["Dan Jurafsky", "James H. Martin"],
    type: "book",
    url: "https://web.stanford.edu/~jurafsky/slp3/",
    sourceType: "academic-book",
    provider: "Stanford University / Prentice Hall",
    relatedTopics: ["Natural Language Processing", "Speech & Audio AI"],
    relatedConcepts: ["tokenization", "n-grams", "sentiment analysis", "machine translation"],
    relevance: "Buku teks komprehensif linguistik komputasional, fonetik, semantik distribusional, dan LLM modern.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "huggingface-transformers": {
    id: "huggingface-transformers",
    title: "Hugging Face Transformers Documentation",
    authors: ["Hugging Face Team"],
    type: "documentation",
    url: "https://huggingface.co/docs/transformers/",
    sourceType: "official-documentation",
    provider: "Hugging Face",
    relatedTopics: ["Natural Language Processing", "Large Language Model", "Generative AI"],
    relatedConcepts: ["AutoModel", "AutoTokenizer", "pipeline", "fine-tuning"],
    relevance: "Dokumentasi pustaka ekosistem sumber terbuka terbesar untuk model fondasi, transfer learning teks, dan multimodal.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "huggingface-datasets": {
    id: "huggingface-datasets",
    title: "Hugging Face Datasets Documentation",
    authors: ["Hugging Face Team"],
    type: "documentation",
    url: "https://huggingface.co/docs/datasets/",
    sourceType: "official-documentation",
    provider: "Hugging Face",
    relatedTopics: ["Data Science", "Natural Language Processing", "Computer Vision"],
    relatedConcepts: ["load_dataset", "streaming", "memory-mapping", "arrow format"],
    relevance: "Panduan resmi memuat, menginspeksi, dan memproses ribuan dataset benchmark publik secara efisien.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sentence-transformers": {
    id: "sentence-transformers",
    title: "Sentence Transformers: Multilingual Sentence, Image, & Subword Embeddings",
    authors: ["Nils Reimers", "Iryna Gurevych"],
    type: "documentation",
    url: "https://www.sbert.net/",
    sourceType: "official-documentation",
    provider: "UKP Lab / Hugging Face",
    relatedTopics: ["Vector Database & Retrieval System", "Natural Language Processing"],
    relatedConcepts: ["dense retrieval", "bi-encoder", "cross-encoder", "semantic search"],
    relevance: "Dokumentasi resmi representasi vektor kalimat untuk sistem pencarian semantik dan Retrieval-Augmented Generation.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "opencv-docs": {
    id: "opencv-docs",
    title: "OpenCV Documentation",
    authors: ["OpenCV team"],
    type: "documentation",
    url: "https://docs.opencv.org/",
    sourceType: "official-documentation",
    provider: "OpenCV Foundation",
    relatedTopics: ["Computer Vision", "Robotics & Embodied AI"],
    relatedConcepts: ["cv2.imread", "color spaces", "morphology", "feature matching"],
    relevance: "Pustaka standar komputasi visi komputer real-time, pengolahan citra digital, dan ekstraksi fitur visual.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Seminal Papers
  "paper-attention": {
    id: "paper-attention",
    title: "Attention Is All You Need",
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N. Gomez", "Łukasz Kaiser", "Illia Polosukhin"],
    type: "paper",
    url: "https://arxiv.org/abs/1706.03762",
    doi: "10.48550/arXiv.1706.03762",
    sourceType: "paper",
    provider: "NeurIPS 2017",
    relatedTopics: ["Large Language Model", "Deep Learning", "Generative AI", "Natural Language Processing"],
    relatedConcepts: ["Scaled Dot-Product Attention", "Multi-Head Attention", "Positional Encoding"],
    relevance: "Paper pelopor yang merevolusi AI modern dengan mengeliminasi rekursi dan memperkenalkan Transformer berbasis atensi murni.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-resnet": {
    id: "paper-resnet",
    title: "Deep Residual Learning for Image Recognition",
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    type: "paper",
    url: "https://arxiv.org/abs/1512.03385",
    doi: "10.48550/arXiv.1512.03385",
    sourceType: "paper",
    provider: "IEEE CVPR 2016",
    relatedTopics: ["Computer Vision", "Deep Learning"],
    relatedConcepts: ["residual connection", "skip connection", "vanishing gradient"],
    relevance: "Paper fundamental yang memecahkan masalah degradasi gradien dan memungkinkan pelatihan jaringan sangat dalam (100+ layer).",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-adam": {
    id: "paper-adam",
    title: "Adam: A Method for Stochastic Optimization",
    authors: ["Diederik P. Kingma", "Jimmy Ba"],
    type: "paper",
    url: "https://arxiv.org/abs/1412.6980",
    doi: "10.48550/arXiv.1412.6980",
    sourceType: "paper",
    provider: "ICLR 2015",
    relatedTopics: ["Deep Learning", "Optimization"],
    relatedConcepts: ["first moment", "second moment", "adaptive learning rate", "bias correction"],
    relevance: "Algoritma optimasi gradien adaptif paling banyak digunakan dalam pelatihan jaringan syaraf tiruan modern.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-dropout": {
    id: "paper-dropout",
    title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
    authors: ["Nitish Srivastava", "Geoffrey Hinton", "Alex Krizhevsky", "Ilya Sutskever", "Ruslan Salakhutdinov"],
    type: "paper",
    url: "https://jmlr.org/papers/v15/srivastava14a.html",
    sourceType: "paper",
    provider: "Journal of Machine Learning Research (JMLR)",
    relatedTopics: ["Deep Learning", "Machine Learning", "Overfitting"],
    relatedConcepts: ["regularization", "co-adaptation", "ensemble approximation"],
    relevance: "Teknik regularisasi kunci yang menonaktifkan neuron acak selama pelatihan untuk mencegah ko-adaptasi dan overfitting.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-nature-dl": {
    id: "paper-nature-dl",
    title: "Deep learning",
    authors: ["Yann LeCun", "Yoshua Bengio", "Geoffrey Hinton"],
    type: "paper",
    url: "https://www.nature.com/articles/nature14539",
    doi: "10.1038/nature14539",
    sourceType: "paper",
    provider: "Nature",
    relatedTopics: ["Deep Learning", "Artificial Intelligence Fundamentals"],
    relatedConcepts: ["representation learning", "backpropagation", "supervised learning"],
    relevance: "Tinjauan komprehensif oleh para pelopor Deep Learning mengenai prinsip dasar komputasi representasi berlapis.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-lora": {
    id: "paper-lora",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    authors: ["Edward J. Hu", "Yelong Shen", "Phillip Wallis", "Zeyuan Allen-Zhu", "Yuanzhi Li", "Shean Wang", "Lu Wang", "Weizhu Chen"],
    type: "paper",
    url: "https://arxiv.org/abs/2106.09685",
    doi: "10.48550/arXiv.2106.09685",
    sourceType: "paper",
    provider: "ICLR 2022",
    relatedTopics: ["Large Language Model", "Generative AI", "Edge AI & TinyML"],
    relatedConcepts: ["parameter-efficient fine-tuning", "rank decomposition", "adapter"],
    relevance: "Metode adaptasi berbobot rendah (PEFT) yang memungkinkan fine-tuning model miliaran parameter dengan komputasi minimal.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-rag": {
    id: "paper-rag",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    authors: ["Patrick Lewis", "Ethan Perez", "Aleksandra Piktus", "Fabio Petroni", "Vladimir Karpukhin", "Naman Goyal", "Heinrich Küttler", "Mike Lewis", "Wen-tau Yih", "Tim Rocktäschel", "Sebastian Riedel", "Douwe Kiela"],
    type: "paper",
    url: "https://arxiv.org/abs/2005.11401",
    doi: "10.48550/arXiv.2005.11401",
    sourceType: "paper",
    provider: "NeurIPS 2020",
    relatedTopics: ["Generative AI", "Vector Database & Retrieval System", "Large Language Model"],
    relatedConcepts: ["dense retrieval", "hallucination mitigation", "parametric vs non-parametric memory"],
    relevance: "Kerangka hibrida yang mengintegrasikan pencarian dokumen berbasis vektor dengan model generasi teks untuk mengeliminasi halusinasi.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Big Data, Databases & MLOps
  "postgresql-docs": {
    id: "postgresql-docs",
    title: "PostgreSQL: The World's Most Advanced Open Source Relational Database",
    authors: ["PostgreSQL Global Development Group"],
    type: "documentation",
    url: "https://www.postgresql.org/docs/",
    sourceType: "official-documentation",
    provider: "PostgreSQL Community",
    relatedTopics: ["Data Engineering & Big Data untuk AI", "Data Analyst"],
    relatedConcepts: ["SQL", "indexing", "ACID", "JSONB", "query optimization"],
    relevance: "Dokumentasi resmi sistem basis data relasional standar industri untuk analitik dan penyimpanan terstruktur.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "spark-docs": {
    id: "spark-docs",
    title: "Apache Spark Documentation",
    authors: ["Apache Software Foundation"],
    type: "documentation",
    url: "https://spark.apache.org/docs/latest/",
    sourceType: "official-documentation",
    provider: "Apache Software Foundation",
    relatedTopics: ["Data Engineering & Big Data untuk AI", "Machine Learning"],
    relatedConcepts: ["RDD", "DataFrame", "Spark SQL", "distributed computing", "partitioning"],
    relevance: "Dokumentasi resmi mesin pemrosesan data terdistribusi skala besar untuk ETL, pembersihan, dan analitik Big Data.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "fastapi-docs": {
    id: "fastapi-docs",
    title: "FastAPI Documentation",
    authors: ["Sebastián Ramírez"],
    type: "documentation",
    url: "https://fastapi.tiangolo.com/",
    sourceType: "official-documentation",
    provider: "FastAPI",
    relatedTopics: ["MLOps & AI Deployment", "AI Agent"],
    relatedConcepts: ["REST API", "Pydantic", "asyncio", "OpenAPI", "Swagger"],
    relevance: "Dokumentasi kerangka kerja web Python performa tinggi berbasis type hints untuk penyajian model AI secara real-time.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "docker-docs": {
    id: "docker-docs",
    title: "Docker Documentation: Empowering App Development for Developers",
    authors: ["Docker Inc."],
    type: "documentation",
    url: "https://docs.docker.com/",
    sourceType: "official-documentation",
    provider: "Docker",
    relatedTopics: ["MLOps & AI Deployment"],
    relatedConcepts: ["Dockerfile", "containerization", "image", "reproducibility"],
    relevance: "Standar industri isolasi lingkungan komputasi dan pembungkusan microservices model kecerdasan buatan.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "mlflow-docs": {
    id: "mlflow-docs",
    title: "MLflow Tracking & Model Registry",
    authors: ["MLflow Core Team"],
    type: "documentation",
    url: "https://mlflow.org/docs/latest/ml/tracking/",
    sourceType: "official-documentation",
    provider: "Linux Foundation / Databricks",
    relatedTopics: ["MLOps & AI Deployment", "Machine Learning"],
    relatedConcepts: ["experiment tracking", "metrics logging", "artifacts", "model registry"],
    relevance: "Platform open-source untuk pencatatan eksperimen, perbandingan performa hyperparameter, dan manajemen siklus hidup model.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Ethics, Governance & Security
  "nist-ai-rmf": {
    id: "nist-ai-rmf",
    title: "NIST Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
    authors: ["National Institute of Standards and Technology (NIST)"],
    type: "standard",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    sourceType: "standard-framework",
    provider: "U.S. Department of Commerce",
    relatedTopics: ["AI Governance & Regulasi", "AI Ethics & Responsible AI", "AI Security & Adversarial Machine Learning"],
    relatedConcepts: ["Govern", "Map", "Measure", "Manage", "trustworthy AI"],
    relevance: "Kerangka kerja standar internasional untuk identifikasi, pengukuran, dan mitigasi risiko sosioteknis dalam siklus hidup AI.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "owasp-ml-top10": {
    id: "owasp-ml-top10",
    title: "OWASP Machine Learning Security Top 10",
    authors: ["OWASP Foundation"],
    type: "standard",
    url: "https://owasp.org/www-project-machine-learning-security-top-10/",
    sourceType: "standard-framework",
    provider: "Open Web Application Security Project (OWASP)",
    relatedTopics: ["AI Security & Adversarial Machine Learning"],
    relatedConcepts: ["adversarial attacks", "data poisoning", "model inversion", "membership inference"],
    relevance: "Taksonomi kerentanan keamanan tertinggi pada sistem machine learning dan panduan proteksi pertahanan.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "owasp-llm-top10": {
    id: "owasp-llm-top10",
    title: "OWASP Top 10 for Large Language Model Applications",
    authors: ["OWASP Foundation"],
    type: "standard",
    url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
    sourceType: "standard-framework",
    provider: "OWASP",
    relatedTopics: ["AI Security & Adversarial Machine Learning", "Large Language Model", "Generative AI"],
    relatedConcepts: ["prompt injection", "insecure output handling", "training data poisoning", "denial of service"],
    relevance: "Standar mitigasi vektor serangan keamanan siber khusus untuk aplikasi yang mengintegrasikan LLM.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "unesco-ai-ethics": {
    id: "unesco-ai-ethics",
    title: "UNESCO Recommendation on the Ethics of Artificial Intelligence",
    authors: ["UNESCO"],
    type: "standard",
    url: "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics",
    sourceType: "standard-framework",
    provider: "UNESCO",
    relatedTopics: ["AI Ethics & Responsible AI", "AI Governance & Regulasi"],
    relatedConcepts: ["human rights", "fairness", "transparency", "accountability"],
    relevance: "Instrumen normatif global pertama yang diadopsi 193 negara mengenai perlindungan hak asasi manusia dan etika dalam AI.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Benchmark Datasets
  "uci-ml-repo": {
    id: "uci-ml-repo",
    title: "UCI Machine Learning Repository",
    authors: ["University of California, Irvine"],
    type: "documentation",
    url: "https://archive.ics.uci.edu/",
    sourceType: "benchmark-dataset",
    provider: "UC Irvine",
    relatedTopics: ["Machine Learning", "Data Science"],
    relatedConcepts: ["tabular benchmark", "classification datasets", "regression datasets"],
    relevance: "Repositori dataset publik resmi tertua dan paling diakui untuk eksperimen dan pembuktian algoritma machine learning.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "openml-repo": {
    id: "openml-repo",
    title: "OpenML: Open Machine Learning Benchmark Platform",
    authors: ["OpenML Community"],
    type: "documentation",
    url: "https://www.openml.org/",
    sourceType: "benchmark-dataset",
    provider: "OpenML Foundation",
    relatedTopics: ["Machine Learning", "AutoML & Neural Architecture Search"],
    relatedConcepts: ["reproducibility", "datasets", "runs", "benchmarking"],
    relevance: "Platform ekosistem data machine learning global untuk eksperimen sains data kolaboratif dan terstandarisasi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-toy-datasets": {
    id: "sklearn-toy-datasets",
    title: "scikit-learn Toy datasets Reference",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/datasets/toy_dataset.html",
    sourceType: "benchmark-dataset",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Science"],
    relatedConcepts: ["load_iris", "load_diabetes", "load_digits", "load_wine", "load_breast_cancer"],
    relevance: "Dokumentasi dataset bawaan scikit-learn yang siap dimuat seketika tanpa memerlukan unduhan jaringan.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "sklearn-real-world-datasets": {
    id: "sklearn-real-world-datasets",
    title: "scikit-learn Real world datasets",
    authors: ["scikit-learn developers"],
    type: "documentation",
    url: "https://scikit-learn.org/stable/datasets/real_world.html",
    sourceType: "benchmark-dataset",
    provider: "scikit-learn",
    relatedTopics: ["Machine Learning", "Data Science"],
    relatedConcepts: ["fetch_california_housing", "fetch_covtype", "fetch_rcv1"],
    relevance: "Dokumentasi dataset skala besar nyata untuk benchmarking model regresi dan klasifikasi multi-dimensi.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Recommender Systems
  "recsys-handbook": {
    id: "recsys-handbook",
    title: "Recommender Systems Handbook",
    authors: ["Francesco Ricci", "Lior Rokach", "Bracha Shapira"],
    type: "book",
    url: "https://link.springer.com/book/10.1007/978-1-4899-7637-6",
    sourceType: "academic-book",
    provider: "Springer",
    relatedTopics: ["Recommendation System", "Machine Learning"],
    relatedConcepts: ["collaborative filtering", "content-based", "matrix factorization", "hybrid recommender"],
    relevance: "Buku rujukan akademik standar emas yang merangkum seluruh fondasi matematika, algoritma faktorisasi matriks, dan evaluasi sistem rekomendasi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "implicit-docs": {
    id: "implicit-docs",
    title: "Implicit: Fast Python Collaborative Filtering for Implicit Datasets",
    authors: ["Ben Frederickson"],
    type: "documentation",
    url: "https://implicit.readthedocs.io/en/latest/",
    sourceType: "official-documentation",
    provider: "Ben Frederickson",
    relatedTopics: ["Recommendation System"],
    relatedConcepts: ["implicit feedback", "alternating least squares (ALS)", "BPR", "Cython GPU"],
    relevance: "Dokumentasi resmi pustaka komputasi faktorisasi matriks implicit feedback teroptimasi C++ dan CUDA.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "surprise-docs": {
    id: "surprise-docs",
    title: "Surprise: A Python scikit for Recommender Systems",
    authors: ["Nicolas Hug"],
    type: "documentation",
    url: "https://surpriselib.com/",
    sourceType: "official-documentation",
    provider: "Nicolas Hug",
    relatedTopics: ["Recommendation System"],
    relatedConcepts: ["SVD", "SVD++", "k-NN baseline", "RMSE", "cross-validation"],
    relevance: "Dokumentasi resmi pustaka Scikit-Learn style untuk evaluasi dan benchmarking algoritma collaborative filtering eksplisit.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Reinforcement Learning
  "sutton-barto": {
    id: "sutton-barto",
    title: "Reinforcement Learning: An Introduction (Second Edition)",
    authors: ["Richard S. Sutton", "Andrew G. Barto"],
    type: "book",
    url: "http://incompleteideas.net/book/the-book-2nd.html",
    sourceType: "academic-book",
    provider: "MIT Press",
    relatedTopics: ["Reinforcement Learning", "Artificial Intelligence Fundamentals"],
    relatedConcepts: ["Markov Decision Process", "Bellman equation", "Q-learning", "policy gradient", "actor-critic"],
    relevance: "Buku teks kanonikal fondasi reinforcement learning dunia: teori matematika MDP, dynamic programming, temporal difference, dan function approximation.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "gymnasium-docs": {
    id: "gymnasium-docs",
    title: "Gymnasium Documentation: Standard API for Reinforcement Learning Environments",
    authors: ["Farama Foundation"],
    type: "documentation",
    url: "https://gymnasium.farama.org/",
    sourceType: "official-documentation",
    provider: "Farama Foundation",
    relatedTopics: ["Reinforcement Learning"],
    relatedConcepts: ["env.step", "env.reset", "action space", "observation space", "reward wrapper"],
    relevance: "Standar industri antarmuka simulasi lingkungan agen pembelajaran penguatan suksesor OpenAI Gym.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "stable-baselines3": {
    id: "stable-baselines3",
    title: "Stable-Baselines3: Reliable Reinforcement Learning Implementations",
    authors: ["Antonin Raffin", "Ashley Hill", "Adam Gleave", "Maximilian Ernestus", "Frode Dahl"],
    type: "documentation",
    url: "https://stable-baselines3.readthedocs.io/",
    sourceType: "official-documentation",
    provider: "DLR / Inria",
    relatedTopics: ["Reinforcement Learning"],
    relatedConcepts: ["PPO", "SAC", "DQN", "A2C", "replay buffer"],
    relevance: "Dokumentasi resmi implementasi PyTorch terverifikasi algoritma model-free RL mutakhir.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Robotics & Embodied AI
  "ros2-docs": {
    id: "ros2-docs",
    title: "ROS 2 Documentation: Robot Operating System",
    authors: ["Open Source Robotics Foundation (OSRF)"],
    type: "documentation",
    url: "https://docs.ros.org/en/rolling/",
    sourceType: "official-documentation",
    provider: "Open Source Robotics Foundation",
    relatedTopics: ["Robotics & Embodied AI"],
    relatedConcepts: ["nodes", "topics", "services", "actions", "DDS middleware", "rclpy"],
    relevance: "Dokumentasi middleware standar de facto robotika modern untuk orkestrasi subsistem sensor, aktuator, dan komputasi AI.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "moveit2-docs": {
    id: "moveit2-docs",
    title: "MoveIt 2: Robotic Manipulation Platform",
    authors: ["PickNik Robotics"],
    type: "documentation",
    url: "https://moveit.picknik.ai/",
    sourceType: "official-documentation",
    provider: "PickNik Robotics",
    relatedTopics: ["Robotics & Embodied AI"],
    relatedConcepts: ["inverse kinematics", "motion planning", "collision checking", "trajectory generation"],
    relevance: "Kerangka kerja standar untuk perencanaan gerak manipulator robotik, penghindaran tabrakan, dan kontrol kinematika.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Speech & Audio AI
  "librosa-docs": {
    id: "librosa-docs",
    title: "Librosa: Audio and Music Processing in Python",
    authors: ["Brian McFee", "Colin Raffel", "Dawen Liang", "Daniel P. W. Ellis"],
    type: "documentation",
    url: "https://librosa.org/doc/latest/",
    sourceType: "official-documentation",
    provider: "Librosa Community",
    relatedTopics: ["Speech & Audio AI"],
    relatedConcepts: ["STFT", "mel-spectrogram", "MFCC", "chroma", "onset detection"],
    relevance: "Dokumentasi resmi analisis sinyal audio digital, transformasi frekuensi-waktu, dan ekstraksi fitur akustik.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "torchaudio-docs": {
    id: "torchaudio-docs",
    title: "TorchAudio: Deep Learning Audio Processing with PyTorch",
    authors: ["PyTorch Core Audio Team"],
    type: "documentation",
    url: "https://pytorch.org/audio/stable/",
    sourceType: "official-documentation",
    provider: "PyTorch Foundation",
    relatedTopics: ["Speech & Audio AI", "Deep Learning"],
    relatedConcepts: ["transforms", "pipelines", "Conformer", "wav2vec 2.0", "CTC loss"],
    relevance: "Dokumentasi integrasi tensor audio terakselerasi GPU untuk pengenalan suara (ASR) dan sintesis wicara (TTS).",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "paper-whisper": {
    id: "paper-whisper",
    title: "Robust Speech Recognition via Large-Scale Weak Supervision",
    authors: ["Alec Radford", "Jong Wook Kim", "Tao Xu", "Greg Brockman", "Christine McLeavey", "Ilya Sutskever"],
    type: "paper",
    url: "https://arxiv.org/abs/2212.04356",
    doi: "10.48550/arXiv.2212.04356",
    sourceType: "paper",
    provider: "OpenAI",
    relatedTopics: ["Speech & Audio AI", "Large Language Model"],
    relatedConcepts: ["encoder-decoder audio transformer", "multilingual ASR", "speech translation", "voice activity detection"],
    relevance: "Paper seminal model Whisper yang mengubah lanskap transkripsi wicara global dengan pelatihan 680,000 jam audio multibahasa.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Time Series Forecasting
  "statsmodels-docs": {
    id: "statsmodels-docs",
    title: "statsmodels: Statistical Models, Hypothesis Tests, and Data Exploration",
    authors: ["statsmodels Developers"],
    type: "documentation",
    url: "https://www.statsmodels.org/stable/",
    sourceType: "official-documentation",
    provider: "statsmodels",
    relatedTopics: ["Time Series Forecasting", "Data Science"],
    relatedConcepts: ["ARIMA", "SARIMAX", "stationarity test", "ADF test", "ACF and PACF"],
    relevance: "Dokumentasi resmi ekonometrika dan pemodelan statistik deret waktu klasik berketelitian tinggi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "prophet-docs": {
    id: "prophet-docs",
    title: "Prophet: Automatic Forecasting Procedure",
    authors: ["Sean J. Taylor", "Benjamin Letham"],
    type: "documentation",
    url: "https://facebook.github.io/prophet/",
    sourceType: "official-documentation",
    provider: "Meta Open Source",
    relatedTopics: ["Time Series Forecasting"],
    relatedConcepts: ["additive models", "trend changepoints", "seasonality", "holiday effects"],
    relevance: "Dokumentasi pustaka peramalan aditif skala besar yang tangguh terhadap data hilang dan perubahan tren.",
    verified: true,
    lastChecked: "2026-09-15",
  },

  // Vector Database & Retrieval
  "faiss-docs": {
    id: "faiss-docs",
    title: "Faiss: A Library for Efficient Similarity Search and Clustering of Dense Vectors",
    authors: ["Matthijs Douze", "Alexandr Guzhva", "Chengqi Deng", "Jeff Johnson", "Hervé Jégou"],
    type: "documentation",
    url: "https://github.com/facebookresearch/faiss",
    sourceType: "official-documentation",
    provider: "Meta Fundamental AI Research (FAIR)",
    relatedTopics: ["Vector Database & Retrieval System"],
    relatedConcepts: ["IndexFlatL2", "IndexIVFFlat", "Product Quantization (PQ)", "HNSW", "GPU acceleration"],
    relevance: "Standar emas algoritma pencarian tetangga terdekat perkiraan (ANN) untuk embedding miliaran vektor.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "chromadb-docs": {
    id: "chromadb-docs",
    title: "Chroma Documentation: The AI-native Open-source Embedding Database",
    authors: ["Chroma Core Team"],
    type: "documentation",
    url: "https://docs.trychroma.com/",
    sourceType: "official-documentation",
    provider: "Chroma",
    relatedTopics: ["Vector Database & Retrieval System", "Generative AI"],
    relatedConcepts: ["collections", "embeddings", "query", "metadata filtering", "distance metrics"],
    relevance: "Dokumentasi resmi basis data vektor modular ringan untuk aplikasi RAG dan agen AI modern.",
    verified: true,
    lastChecked: "2026-09-15",
  },
  "qdrant-docs": {
    id: "qdrant-docs",
    title: "Qdrant: Vector Database for Next-Generation AI",
    authors: ["Qdrant Team"],
    type: "documentation",
    url: "https://qdrant.tech/documentation/",
    sourceType: "official-documentation",
    provider: "Qdrant",
    relatedTopics: ["Vector Database & Retrieval System"],
    relatedConcepts: ["payload filtering", "HNSW graph", "gRPC", "distributed vector search", "quantization"],
    relevance: "Dokumentasi resmi basis data vektor performa tinggi berbasis Rust untuk pencarian semantik skala produksi.",
    verified: true,
    lastChecked: "2026-09-15",
  },
};
